// Writes packages/core/src/font/encoding/adobeGlyphList.ts from the Adobe Glyph List files of adobe-type-tools/agl-aglfn.
// Run with: node scripts/generateGlyphList.ts <directory holding glyphlist.txt, zapfdingbats.txt and LICENSE.md from the commit below>

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const REPOSITORY = 'https://github.com/adobe-type-tools/agl-aglfn';
const COMMIT = '4036a9ca80a62f64f9de4f7321a9a045ad0ecfd6';
const INPUTS = {
  'glyphlist.txt': 'a3b2f61ced9f3644cc0d4ecde5c59df34ca286c689d9484a43a710a81c466789',
  'zapfdingbats.txt': 'f6394e3cb8a447e84a1dad75d4baaf2aa7f45dc104faf369f4720e1a774ef2dc',
  'LICENSE.md': '58147d341e7a34aa2196862395a34d2fd95716c41d5ed26efb59ab0e12f92089',
} as const;
const COPYRIGHT = 'Copyright 2002-2019 Adobe (http://www.adobe.com/).';
const OUTPUT = path.join(import.meta.dirname, '../packages/core/src/font/encoding/adobeGlyphList.ts');

const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

const readInput = async (directory: string, name: keyof typeof INPUTS): Promise<string> => {
  const bytes = await readFile(path.join(directory, name));
  if (sha256(bytes) !== INPUTS[name]) throw new Error(`${name} does not have the sha256 of the file at ${COMMIT}`);
  return bytes.toString('utf8');
};

// Each data line is `name;XXXX` or `name;XXXX XXXX…`: a glyph name and its Unicode values as four uppercase hexadecimal digits.
const dataLines = (text: string): string[] => {
  const lines = text.split('\n').filter(line => line !== '' && !line.startsWith('#'));
  for (const line of lines) if (!/^[A-Za-z0-9]+;[0-9A-F]{4}( [0-9A-F]{4})*$/u.test(line)) throw new Error(`unexpected line: ${line}`);
  return lines;
};

// The licence as one line per paragraph, words unchanged, so that the comment keeps each sentence on one line.
const paragraphs = (text: string): string[] =>
  text
    .split(/\n\s*\n/u)
    .map(paragraph => paragraph.replaceAll(/\s+/gu, ' ').trim())
    .filter(paragraph => paragraph !== '');

const main = async (): Promise<void> => {
  const [directory] = process.argv.slice(2);
  if (directory === undefined) throw new Error('usage: node scripts/generateGlyphList.ts <input directory>');
  const glyphs = dataLines(await readInput(directory, 'glyphlist.txt'));
  const dingbats = dataLines(await readInput(directory, 'zapfdingbats.txt'));
  const licence = paragraphs(await readInput(directory, 'LICENSE.md'));
  const output = [
    `// Generated by scripts/generateGlyphList.ts from the Adobe Glyph List: do not edit.`,
    `// Source: ${REPOSITORY} at commit ${COMMIT}, glyphlist.txt (sha256 ${INPUTS['glyphlist.txt']}) and zapfdingbats.txt (sha256 ${INPUTS['zapfdingbats.txt']}), with their comment lines removed.`,
    `// ${COPYRIGHT}`,
    `// Licensed under the BSD 3-Clause License, as LICENSE.md (sha256 ${INPUTS['LICENSE.md']}) states it:`,
    ...licence.map(paragraph => `// ${paragraph}`),
    '',
    '/** The Adobe Glyph List, one `name;XXXX` line per glyph name with its Unicode values in hexadecimal. */',
    `export const ADOBE_GLYPH_LIST = \`${glyphs.join('\n')}\`;`,
    '',
    '/** The ITC Zapf Dingbats Glyph List, in the same form. */',
    `export const ZAPF_DINGBATS_GLYPH_LIST = \`${dingbats.join('\n')}\`;`,
    '',
  ].join('\n');
  await writeFile(OUTPUT, output);
  console.log(`wrote ${String(glyphs.length)} glyph names and ${String(dingbats.length)} Zapf Dingbats names to ${OUTPUT}`);
};

await main();
