// Writes packages/core/src/color/srgbProfileData.ts from tests/fixtures/icc/sRGB2014.icc: the profile's bytes as hexadecimal, unmodified.
// Run with: node scripts/generateSrgbProfile.ts

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const SOURCE = 'https://registry.color.org/rgb-registry/profiles/sRGB2014.icc';
const LICENCE = 'https://registry.color.org/profile-library/#license';
const SOURCE_SHA256 = '384b832de3412066743b52a75ee906b6fb9fb8d9e09e936fc2c43223815c6e0a';
const INPUT = path.join(import.meta.dirname, '../tests/fixtures/icc/sRGB2014.icc');
const OUTPUT = path.join(import.meta.dirname, '../packages/core/src/color/srgbProfileData.ts');

const main = async (): Promise<void> => {
  const bytes = await readFile(INPUT);
  if (createHash('sha256').update(bytes).digest('hex') !== SOURCE_SHA256) throw new Error('sRGB2014.icc does not have the sha256 of the registry file');
  const output = [
    '// Generated by scripts/generateSrgbProfile.ts: do not edit.',
    `// The bytes of the International Color Consortium's sRGB2014.icc (${SOURCE}, sha256 ${SOURCE_SHA256}, retrieved 2026-09-29), unmodified.`,
    `// Licence (${LICENCE}): "This profile is made available by the International Color Consortium, and may be copied, distributed, embedded, made, used, and sold without restriction. Altered versions of this profile shall have the original identification and copyright information removed and shall not be misrepresented as the original profile."`,
    '',
    `/** The ${bytes.length.toLocaleString('en')} bytes of sRGB2014.icc as lowercase hexadecimal, two digits per byte. */`,
    `export const SRGB2014_HEX =\n  '${bytes.toString('hex')}';`,
    '',
  ].join('\n');
  await writeFile(OUTPUT, output);
  console.log(`wrote ${String(bytes.length)} profile bytes to ${OUTPUT}`);
};

await main();
