// Writes packages/core/src/inspect/text/equivalentIdeographs.ts from the Unicode Character Database file EquivalentUnifiedIdeograph.txt.
// Run with: node scripts/generateEquivalentIdeographs.ts <directory holding EquivalentUnifiedIdeograph.txt from the URL below>

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const SOURCE = 'https://www.unicode.org/Public/18.0.0/ucd/EquivalentUnifiedIdeograph.txt';
const VERSION = '18.0.0';
const SHA256 = 'c86c80f6a0d1d47c9a5aadfbf1c26f1a732d662d9ccb0ed2d397919ecc47bf72';
const COPYRIGHT = '© 2026 Unicode®, Inc.';
const OUTPUT = path.join(import.meta.dirname, '../packages/core/src/inspect/text/equivalentIdeographs.ts');

const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

// Each data line is `XXXX ; YYYY # name` or `XXXX..XXXX ; YYYY # names`: a code point or range and its equivalent unified ideograph, 4 to 6 hexadecimal digits each.
const mappings = (text: string): string[] => {
  const lines = text.split('\n').filter(line => line.trim() !== '' && !line.startsWith('#'));
  return lines.flatMap(line => {
    const match = /^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([0-9A-F]{4,6})\s*#/u.exec(line);
    if (match === null) throw new Error(`unexpected line: ${line}`);
    const [, first = '', last = first, target = ''] = match;
    const [start, end] = [Number.parseInt(first, 16), Number.parseInt(last, 16)];
    return Array.from({ length: end - start + 1 }, (_, offset) => `${(start + offset).toString(16).toUpperCase().padStart(4, '0')};${target}`);
  });
};

const main = async (): Promise<void> => {
  const [directory] = process.argv.slice(2);
  if (directory === undefined) throw new Error('usage: node scripts/generateEquivalentIdeographs.ts <input directory>');
  const bytes = await readFile(path.join(directory, 'EquivalentUnifiedIdeograph.txt'));
  if (sha256(bytes) !== SHA256) throw new Error(`EquivalentUnifiedIdeograph.txt does not have the sha256 of the file at ${SOURCE}`);
  const text = bytes.toString('utf8');
  if (!text.includes(`# ${COPYRIGHT}`)) throw new Error('the copyright line of the file has changed');
  const lines = mappings(text);
  const output = [
    '// Generated by scripts/generateEquivalentIdeographs.ts from the Unicode Character Database: do not edit.',
    `// Source: ${SOURCE} (Unicode ${VERSION}, sha256 ${SHA256}), with its comment lines removed and its ranges written out one code point per line.`,
    `// ${COPYRIGHT}`,
    '// Distributed under the Unicode License v3, whose text is in THIRD-PARTY-NOTICES.md at the root of this package.',
    '',
    '/** The Equivalent_Unified_Ideograph property: one `XXXX;YYYY` line per CJK radical or stroke with its equivalent unified ideograph, both in hexadecimal. */',
    `export const EQUIVALENT_UNIFIED_IDEOGRAPHS = \`${lines.join('\n')}\`;`,
    '',
  ].join('\n');
  await writeFile(OUTPUT, output);
  console.log(`wrote ${String(lines.length)} code points to ${OUTPUT}`);
};

await main();
