// Writes packages/core/src/inspect/text/verticalOrientation.ts from the Unicode Character Database file VerticalOrientation.txt.
// Run with: node scripts/generateVerticalOrientation.ts <directory holding VerticalOrientation.txt from the URL below>

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const SOURCE = 'https://www.unicode.org/Public/18.0.0/ucd/VerticalOrientation.txt';
const VERSION = '18.0.0';
const SHA256 = '0803e09669d7aa7137de678e55b848bd418c6632694fa1b05f0b40941103c748';
const COPYRIGHT = '© 2026 Unicode®, Inc.';
const OUTPUT = path.join(import.meta.dirname, '../packages/core/src/inspect/text/verticalOrientation.ts');

const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

// Each data line is `XXXX ; V # name` or `XXXX..XXXX ; V # names`: a code point or range and its Vertical_Orientation value, U, R, Tu or Tr. Only Tu and Tr are kept.
const transformed = (text: string): string[] => {
  const lines = text.split('\n').filter(line => line.trim() !== '' && !line.startsWith('#'));
  return lines.flatMap(line => {
    const match = /^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*(U|R|Tu|Tr)\s*#/u.exec(line);
    if (match === null) throw new Error(`unexpected line: ${line}`);
    const [, first = '', last = first, value = ''] = match;
    return value === 'Tu' || value === 'Tr' ? [`${first};${last};${value}`] : [];
  });
};

const main = async (): Promise<void> => {
  const [directory] = process.argv.slice(2);
  if (directory === undefined) throw new Error('usage: node scripts/generateVerticalOrientation.ts <input directory>');
  const bytes = await readFile(path.join(directory, 'VerticalOrientation.txt'));
  if (sha256(bytes) !== SHA256) throw new Error(`VerticalOrientation.txt does not have the sha256 of the file at ${SOURCE}`);
  const text = bytes.toString('utf8');
  if (!text.includes(`# ${COPYRIGHT}`)) throw new Error('the copyright line of the file has changed');
  const lines = transformed(text);
  const output = [
    '// Generated by scripts/generateVerticalOrientation.ts from the Unicode Character Database: do not edit.',
    `// Source: ${SOURCE} (Unicode ${VERSION}, sha256 ${SHA256}), with only its Tu and Tr lines kept, their comments removed.`,
    `// ${COPYRIGHT}`,
    '// Distributed under the Unicode License v3, whose text is in THIRD-PARTY-NOTICES.md at the root of this package.',
    '',
    '/** The code points whose Vertical_Orientation is Tu or Tr (UAX #50), which fonts draw with a vertical alternate in vertical text: one `FIRST;LAST;VALUE` line per range, code points in hexadecimal. */',
    `export const TRANSFORMED_VERTICAL_ORIENTATION = \`${lines.join('\n')}\`;`,
    '',
  ].join('\n');
  await writeFile(OUTPUT, output);
  console.log(`wrote ${String(lines.length)} ranges to ${OUTPUT}`);
};

await main();
