// Writes packages/core/src/inspect/text/eastAsianWidth.ts from the Unicode Character Database file EastAsianWidth.txt.
// Run with: node scripts/generateEastAsianWidth.ts <directory holding EastAsianWidth.txt from the URL below>

import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const SOURCE = 'https://www.unicode.org/Public/18.0.0/ucd/EastAsianWidth.txt';
const VERSION = '18.0.0';
const SHA256 = 'a0cf29eacd00cfcaec4381c6b7c281685f18dbb4e7ff82b4076ccb342ca839aa';
const COPYRIGHT = '© 2026 Unicode®, Inc.';
const OUTPUT = path.join(import.meta.dirname, '../packages/core/src/inspect/text/eastAsianWidth.ts');

const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

const hex = (codePoint: number): string => codePoint.toString(16).toUpperCase().padStart(4, '0');

// Each data line is `XXXX ; V # name` or `XXXX..XXXX ; V # names`: a code point or range and its East_Asian_Width value, A, F, H, N, Na or W. Only F and W are kept, with adjacent ranges joined.
const wide = (text: string): string[] => {
  const lines = text.split('\n').filter(line => line.trim() !== '' && !line.startsWith('#'));
  const ranges: [number, number][] = [];
  for (const line of lines) {
    const match = /^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*(A|F|H|N|Na|W)\s*#/u.exec(line);
    if (match === null) throw new Error(`unexpected line: ${line}`);
    const [, first = '', last = first, value = ''] = match;
    if (value !== 'F' && value !== 'W') continue;
    const [start, end] = [Number.parseInt(first, 16), Number.parseInt(last, 16)];
    const previous = ranges.at(-1);
    if (previous !== undefined && previous[1] + 1 === start) previous[1] = end;
    else ranges.push([start, end]);
  }
  return ranges.map(([start, end]) => `${hex(start)};${hex(end)}`);
};

const main = async (): Promise<void> => {
  const [directory] = process.argv.slice(2);
  if (directory === undefined) throw new Error('usage: node scripts/generateEastAsianWidth.ts <input directory>');
  const bytes = await readFile(path.join(directory, 'EastAsianWidth.txt'));
  if (sha256(bytes) !== SHA256) throw new Error(`EastAsianWidth.txt does not have the sha256 of the file at ${SOURCE}`);
  const text = bytes.toString('utf8');
  if (!text.includes(`# ${COPYRIGHT}`)) throw new Error('the copyright line of the file has changed');
  const lines = wide(text);
  const output = [
    '// Generated by scripts/generateEastAsianWidth.ts from the Unicode Character Database: do not edit.',
    `// Source: ${SOURCE} (Unicode ${VERSION}, sha256 ${SHA256}), with only its F and W ranges kept, adjacent ones joined; code points it does not list, which it gives the default N or, unassigned in some CJK blocks, W, are not included.`,
    `// ${COPYRIGHT}`,
    '// Distributed under the Unicode License v3, whose text is in THIRD-PARTY-NOTICES.md at the root of this package.',
    '',
    '/** The code points the file lists with East_Asian_Width F (fullwidth) or W (wide) (UAX #11): one `FIRST;LAST` line per range, in hexadecimal. */',
    `export const FULL_WIDTH_OR_WIDE = \`${lines.join('\n')}\`;`,
    '',
  ].join('\n');
  await writeFile(OUTPUT, output);
  console.log(`wrote ${String(lines.length)} ranges to ${OUTPUT}`);
};

await main();
